server:
  port: 8080
app:
  frontend-url: http://localhost:3000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/capstone1test
    username: root
    password: dabin3775
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: "6gB#Yp!3r8S!jN&fW@zR2Q$V7mLw9zT3Kj^Xx5Nc4VdZ&vQs*W" # JWT secret key
  expiration: 86400000            # 토큰 만료 시간 (ms)

logging:
  level:
    org.springframework.security: DEBUG

mvc:
  cors:
    mappings:
      "/**":
        allowed-origins: "http://localhost:3000"
        allowed-methods: "*"
        allowed-headers: "*"
        allow-credentials: true